### ISSUE TITLE
Quotes (doble, single & others): how to use them with drillster/drone-rsync

### ISSUE THREAD

**Issue by lg007** [Drillster/drone-rsync#13]
Hello,

Again I need some help using the drillster/drone-rsync plugin.

After copying files during the deploy phase, I need to run the following shell command:

``
rsync -avs --delete --ignore-times --filter='-p storage/*/*' /path/to/source/ /path/to/target
``

If I run it from the command line of the target server, it works.

If I add it to the pipeline under `script:` it fails with the following error message:

`unexpected end of filter rule: -p`

I tried many combinations, with single and double quotes and back ticks without any success. I think that the problem lies in the filter itself having so many slashes... 

Any help is appreciated!

**Comment by mjwwit** [comment]
Did you try modifying the shell script from this project to `echo` the command before it runs? This may shed some light on how it's dealing with escaping.
