### ISSUE TITLE
Doc for Drone 1.0

### ISSUE THREAD

**Issue by amatthieu** [Drillster/drone-rsync#14]
Hello,

I'm using the last Drone version and i saw that you don't have any doc on that format.
Could you update it ?

Thx

**Comment by po8digital** [comment]
Would love to figure this one out, any update :)?

**Comment by clozed2u** [comment]
Any update on this?

**Comment by amatthieu** [comment]
I changed my job since i opened this issue and i'm not working on drone anymore.

Sorry about it but i won't do the PR soon enough.

But i remember it is possible and not that hard. You just have to figure what Drone changed from one version to another. It was quite a long time ago so I don't remember and don't have the time to go back in it.

I wish you good luck in this, don't forget to do the PR if you do it yourself ;)

**Comment by mjwwit** [comment]
I'm still running 0.8, with about 40 projects to migrate. I don't know when I'll have the time to move everything. If anyone can do a PR, I'd be very happy!

**Comment by adelowo** [comment]
I will make a PR for this over the weekend. I just migrated my personal CI server to 1.0 and got this plugin working with it. Here is my `.drone.yml` if anyone wants to take a look at a couple of things that changed https://github.com/adelowo/personal-site/blob/ea57057f9a47c063285e0f25690f8bb49d7d621e/.drone.yml
