### ISSUE TITLE
Different ports settings when deploying to multiple hosts

### ISSUE THREAD

**Issue by wushan** [Drillster/drone-rsync#15]
I am using drone-rsync plugin to sync built files to multiple hosts, it works like a charm before we changed the ssh service port on a node to a custom port number.

I know we can specify a port number in config, but can I set ports for each node ?

something like:
10.10.10.1:22
10.10.10.2:32
10.10.10.3:22

**Comment by mjwwit** [comment]
Sadly, this is not possible at the moment. It is not extremely difficult to implement however, if you know your way around shell scripts I'd love a PR for this!

**Comment by mjwwit** [comment]
I've just merged #16 so this should be fixed now.
