### ISSUE TITLE
Latest version doesnt work

### ISSUE THREAD

**Issue by milewski** [Drillster/drone-rsync#22]
Hi all my builds stop working like an hour ago due its get connection denied public/private key fail, I think it was related to the recently merged pull request https://github.com/Drillster/drone-rsync/pull/20

this is the log i get before the crash:

```

Port not specified, using default port 22!
--
2 | $ rsync -az  -r --del -e 'ssh -i /root/.ssh/id -p 22 -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o StrictHostKeyChecking=no' --exclude=.certificates --exclude=.git --exclude=.env --exclude=storage --exclude=traefik/logs --exclude=node_modules ./ *****@*********.cp,:/srv/***** ...
3 | rsync: connection unexpectedly closed (0 bytes received so far) [sender]
4 | rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.3]
```

**Comment by mjwwit** [comment]
That is very unfortunate, I didn't encounter this during my testing. I'll revert the last PR merge.

**Comment by mjwwit** [comment]
I've just reverted the last PR merge and the new version is already pushed to the Docker Hub. Can you check if your builds are working again?

**Comment by milewski** [comment]
Thanks! It's all working again.

My latest logs shows:

```
rsync -az  -r --del -e 'ssh -p 22 -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o StrictHostKeyChecking=no' --exclude=.certificates --exclude=.git --exclude=.env --exclude=storage --exclude=traefik/logs --exclude=node_modules ./ ****@****:/srv/****
```

This was with the broken version:

```
rsync -az  -r --del -e 'ssh -i /root/.ssh/id -p 22 -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o StrictHostKeyChecking=no' --exclude=.certificates --exclude=.git --exclude=.env --exclude=storage --exclude=traefik/logs --exclude=node_modules ./ ****@****:/srv/****
```

I see the only difference was the `-i /root/.ssh/id` perhaps that `id` file doesnt exist? or its content is somewhat invalid?

**Comment by imolein** [comment]
Sorry for commenting on a closed issue and sorry for inconveniences caused by my PR.
I tested this in various ways too, before I made the PR... Also I don't changed how the key was/is written from variable to file, I only added the `-i` option and declared two variables earlier. Really strange...
I'll try to reproduce this and maybe make another PR.
