### ISSUE TITLE
Problem with setting private key

### ISSUE THREAD

**Issue by cad** [Drillster/drone-rsync#3]
Hello there,

It's written in the [docs](https://github.com/Drillster/drone-rsync/blob/master/DOCS.md) that `RSYNC_USER` secret can be used instead of specifiying the key in the `.drone.yml` file.
> 
> The following secret values can be set to configure the plugin:
> 
> RSYNC_USER - corresponds to user
> RSYNC_KEY - corresponds to key
> 

But when I do that and run `drone exec`.

I get the following error.

`No private key specified!`

**Comment by mjwwit** [comment]
Thanks for reporting this! It seems the docs are outdated. Drone recently changed the way it injects secrets into plugin containers. You now have to use interpolated secrets in your `.drone.yml` file like so:

```yml
pipeline:
  rsync:
    user: ${RSYNC_USER}
    key: ${RSYNC_KEY}
```

Where `RSYNC_USER` and `RSYNC_KEY` are your secrets (as they are now).
For more info on this change, please read: http://discourse.drone.io/t/secret-change-back-to-interpolation/189

I will update the docs asap.

**Comment by alicebob** [comment]
Hmmm, these variables are confusing :/

This is with a drone build from master a few hours ago:

I add a id_rsa.pub file as you do in the docs.
I use that in my .drone.yml as (any of these):

    key: ${KEY}
    key: '${KEY}'
    key: "${KEY}"

All of them generate this rsync command: 

```
Port not specified, using default port 22!
$ rsync -az  -e 'ssh -p 22 -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o StrictHostKeyChecking=no' /my/build.tgz fileserver@some.server:build/build.tgz ...
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.2]
```
And this from the server:
```
   Mar 30 22:07:23 machine sshd[6388]: Received disconnect from 111.222.111.222: 11:  [preauth]
```

Any idea how to add a private key in the latest drone? Thanks!
