### ISSUE TITLE
Support same-host rsync (folder-to-folder)

### ISSUE THREAD

**Issue by lbeltrame** [Drillster/drone-rsync#30]
As the subject says, sometimes rsync is used to transfer files from one local directory to another, without having to go remote. 

An example use case is from static site generators. You can just copy over your tree from `public/` or whatever the built site is generated into to another local folder (which is actually a host folder mounted in the image).

There's no need to go through different hosts in this case, and most docker images used by drone don't have rsync installed.

**Comment by mjwwit** [comment]
Could you please explain why this plugin should offer that functionality over just using one of the many Docker Hub rsync images (https://hub.docker.com/search?q=rsync&type=image)?

**Comment by lbeltrame** [comment]
Good point. No need to add existing complexity when something already works.
