### ISSUE TITLE
support arm64

### ISSUE THREAD

**Issue by johnwmail** [Drillster/drone-rsync#38]
As title, please consider support arm64 platform, thanks.
![image](https://github.com/user-attachments/assets/b527e5f7-b50c-47b9-b292-fc03a61deb66)

**Comment by mjwwit** [comment]
I have no use case for this myself, but I'll accept a pull-request that adds support if you're up for it.

**Comment by mjwwit** [comment]
An arm64 version is now published on Docker Hub
