### ISSUE TITLE
Support for pre-upload script

### ISSUE THREAD

**Issue by misuzu** [Drillster/drone-rsync#7]
I would like to create some directory structure and upload artifacts there, but ```rsync``` can't do that and i forced to use ```appleboy/drone-ssh plugin``` earlier in pipeline just to run ```mkdir -p```. Thats ugly.
Would be great if there were a way to execute commands before ```rsync``` upload.

**Comment by misuzu** [comment]
Yes, that should work, thanks!
Anyway, please consider some option for running ```mkdir -p $TARGET``` before upload (```create_target: true``` for example) if pre-upload script is too much.

**Comment by mjwwit** [comment]
I agree that it would add some value in certain cases. I'll add it when I get around to it. You can also speed things up by making a pull-request.

**Comment by jessequinn** [comment]
add new pull request for this.

#21
