### ISSUE TITLE
how to solve ; in script

### ISSUE THREAD

**Issue by rinetd** [Drillster/drone-rsync#9]
like this command:
```
script:
      - sed -i "s|'hostname'       => .*|'hostname'       => 'mysql' ，|g" config.php
```
in this  scrip  the sed command will separate two commands by **，**

 `sed -i "s|'hostname' => .*|'hostname' => 'mysql' && |g" config.php `

how to solve it?

**Comment by mjwwit** [comment]
Internally, Drone passes environment variables that are lists as a string separated by `,`s. This is probably causing the problem you are describing as one of your commands contains a `,`. We will need to work out some form of escaping syntax to allow this functionality. Are you by any chance familiar with Bash scripting? I'd love a PR for this.

**Comment by rinetd** [comment]
thankyou you,   \\  \"  \’  \,  \;

**Comment by rinetd** [comment]
sed -i -r "/'password'/s/'[^']*'/'mypassword'/" /docker/apache/php5/test/application/database.php && cat /usr/local/upload.sh ...
/usr/local/upload.sh: eval: line 121: unexpected EOF while looking for matching `"'
/usr/local/upload.sh: eval: line 122: syntax error: unexpected end of file

**Comment by mjwwit** [comment]
Can you escape those `'`s? E.g. does `\'` work?

**Comment by mjwwit** [comment]
Let me know if this is still an issue, if not I'll close it.

**Comment by rinetd** [comment]
i have solve it   https://github.com/rinetd/drone-rsync

**Comment by mjwwit** [comment]
You've solved it by building your own plugin? You could've just made a pull-request... Either way this can be closed now.

**Comment by rinetd** [comment]
because i don't how to fix it by shell script
